### ISSUE TITLE
[Warning] Don't revert

### ISSUE THREAD

**Issue by dhanifudin** [polinema-gui/tugas-2015-02-Aldha#1]
@Aldha Jangan melakukan revert jika tidak diperlukan, revert digunakan untuk kembali ke versi history sebelumnya

**Comment by Aldha** [comment]
@dhanifudin Pak gimana, soalnya repositorinya tadi kosong

**Comment by dhanifudin** [comment]
@Aldha repository menjadi kosong karena kamu melakukan revert. Tunggu sebentar saya akan reset repositorynya

**Comment by dhanifudin** [comment]
@Aldha repositorynya sudah saya reset, silahkan melanjutkan pengerjaan  tugasnya :+1:
